name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
      - 'breaking change'
  minor:
    labels:
      - 'minor'
  default: patch

categories:
  - title: 🏆 Highlights
    labels: highlight
  - title: ✨ Features
    labels:
      - feature
      - enhancement
  - title: 🚀 Performance improvements
    labels: performance
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bugfix
      - bug

  - title: '🧰 Maintenance'
    labels: chore
  - title: 📖 Documentation
    labels: documentation
  - title: 🛠️ Other improvements
    labels: internal

exclude-labels:
  - skip changelog
  - release

replacers:
  # Remove conventional commits from titles
  - search: '/- (build|chore|ci|depr|docs|feat|fix|perf|refactor|release|test)(\(.*\))?(\!)?\: /g'
    replace: '- '

template: |
  $CHANGES
