name: "Code Embedder"
description: "This is an action that updates README with up-to-date code snippets."
author: Katerina Vankova
branding:
  icon: "code"
  color: "blue"

runs:
  using: docker
  image: Dockerfile
