name: code-embedder-example

on: pull_request

jobs:
  code-embedder-example:
    name: "Example code embedder"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run code embedder
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.EMBED_TOKEN }}
