name: Check PR title

on:
  pull_request:
    types: [edited]

permissions:
  pull-requests: write

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
