name: code-embedder-example

on:
  push:

jobs:
  code-embedder-example:
    name: "Test: Code Embedder"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Code Embedder
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes if any
        run: |
          if [[ -n $(git status -s) ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add README.md
            git commit -m "Update README.md"
            git push
          fi
      
      
